/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto2.vista;

import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListModel;
import proyecto2.controlador.CategoriaControlador;
import proyecto2.controlador.ImagenControlador;
import proyecto2.controlador.UsuarioControlador;
import proyecto2.handlersImage.BMPtoJPEGImage;
import proyecto2.handlersImage.JPEGImageCopy;
import proyecto2.handlersImage.JPEGImageHandlerBN;
import proyecto2.handlersImage.JPEGImageHandlerColors;
import proyecto2.handlersImage.JPEGImageHandlerRotator;
import proyecto2.handlersImage.JPEGtoBMPImage;
import proyecto2.hilos.HiloC;
import proyecto2.hilos.HiloCN;
import proyecto2.hilos.HiloD;
import proyecto2.hilos.HiloT;
import proyecto2.hilos.Principal;
import proyecto2.modelo.Imagen;
import proyecto2.modelo.Usuario;


/**
 *
 * @author JD
 */
public class Convertidor extends javax.swing.JFrame implements Runnable{

    /**
     * Creates new form Convertidor
     */
    
    UsuarioControlador userC = new UsuarioControlador();
    CategoriaControlador categoriaC = new CategoriaControlador();
    ImagenControlador imagenC = new ImagenControlador();
    
    DefaultListModel<String> modelo = new DefaultListModel<>();
    
    public Convertidor() {
        initComponents();
        this.getContentPane().setBackground(new Color(255,210,129));
        DatosUsuario();
        LlenarCola();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        opcionesI = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbUser = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cmbCategoria = new javax.swing.JComboBox<>();
        btnAgregar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        list = new javax.swing.JList<>();
        jPanel3 = new javax.swing.JPanel();
        chk1 = new javax.swing.JCheckBox();
        chk2 = new javax.swing.JCheckBox();
        chk3 = new javax.swing.JCheckBox();
        chk4 = new javax.swing.JCheckBox();
        chk5 = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        btnEjecutar = new javax.swing.JButton();
        proB = new javax.swing.JProgressBar();
        jScrollPane2 = new javax.swing.JScrollPane();
        textA = new javax.swing.JTextArea();
        lblImages = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 242, 129));

        jPanel1.setBackground(new java.awt.Color(255, 210, 129));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("USUARIO");

        cmbUser.setBackground(new java.awt.Color(255, 221, 154));
        cmbUser.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cmbUser.setForeground(new java.awt.Color(0, 0, 0));
        cmbUser.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbUserItemStateChanged(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("CATEGORIA");

        cmbCategoria.setBackground(new java.awt.Color(255, 221, 154));
        cmbCategoria.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cmbCategoria.setForeground(new java.awt.Color(0, 0, 0));

        btnAgregar.setBackground(new java.awt.Color(255, 221, 154));
        btnAgregar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(0, 0, 0));
        btnAgregar.setText("AGREGAR");
        btnAgregar.setFocusPainted(false);
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnRegresar.setBackground(new java.awt.Color(255, 221, 154));
        btnRegresar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(0, 0, 0));
        btnRegresar.setText("REGRESAR");
        btnRegresar.setFocusPainted(false);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnRegresar)
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbUser, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(53, 53, 53)
                .addComponent(jLabel2)
                .addGap(43, 43, 43)
                .addComponent(cmbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85)
                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(cmbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar)
                    .addComponent(btnRegresar))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 233, 179));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("COLA DE PROCESAMIENTO");

        list.setBackground(new java.awt.Color(255, 233, 179));
        list.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        list.setForeground(new java.awt.Color(0, 0, 0));
        list.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        list.setFocusable(false);
        list.setRequestFocusEnabled(false);
        list.setSelectionBackground(new java.awt.Color(255, 233, 179));
        list.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(list);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 244, 203));

        chk1.setBackground(new java.awt.Color(255, 244, 203));
        chk1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        chk1.setForeground(new java.awt.Color(0, 0, 0));
        chk1.setText("JPEG A BMP Y VICEVERSA");
        chk1.setFocusPainted(false);
        chk1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk1ActionPerformed(evt);
            }
        });

        chk2.setBackground(new java.awt.Color(255, 244, 203));
        chk2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        chk2.setForeground(new java.awt.Color(0, 0, 0));
        chk2.setText("COPIA JPEG");
        chk2.setFocusPainted(false);

        chk3.setBackground(new java.awt.Color(255, 244, 203));
        chk3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        chk3.setForeground(new java.awt.Color(0, 0, 0));
        chk3.setText("ROJO - VERDE - AZUL - SEPIA");
        chk3.setFocusPainted(false);

        chk4.setBackground(new java.awt.Color(255, 244, 203));
        chk4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        chk4.setForeground(new java.awt.Color(0, 0, 0));
        chk4.setText("MODIFICAR IMAGEN");
        chk4.setFocusPainted(false);

        chk5.setBackground(new java.awt.Color(255, 244, 203));
        chk5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        chk5.setForeground(new java.awt.Color(0, 0, 0));
        chk5.setText("BLANCO Y NEGRO");
        chk5.setFocusPainted(false);

        jPanel4.setBackground(new java.awt.Color(255, 244, 203));

        btnEjecutar.setBackground(new java.awt.Color(255, 221, 154));
        btnEjecutar.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        btnEjecutar.setForeground(new java.awt.Color(0, 0, 0));
        btnEjecutar.setText("EJECUTAR EN PARALELO");
        btnEjecutar.setFocusPainted(false);
        btnEjecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEjecutarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 31, Short.MAX_VALUE)
                .addComponent(btnEjecutar))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(89, Short.MAX_VALUE)
                .addComponent(btnEjecutar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
        );

        proB.setBackground(new java.awt.Color(255, 233, 179));
        proB.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        proB.setForeground(new java.awt.Color(255, 210, 129));
        proB.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        proB.setStringPainted(true);

        textA.setEditable(false);
        textA.setBackground(new java.awt.Color(255, 244, 203));
        textA.setColumns(20);
        textA.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        textA.setForeground(new java.awt.Color(0, 0, 0));
        textA.setRows(5);
        textA.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane2.setViewportView(textA);

        lblImages.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblImages.setForeground(new java.awt.Color(0, 0, 0));
        lblImages.setText("0 / 0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(proB, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chk5)
                                    .addComponent(chk4)
                                    .addComponent(chk2)
                                    .addComponent(chk1)
                                    .addComponent(chk3))
                                .addGap(67, 67, 67)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(lblImages)
                        .addGap(313, 313, 313))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(chk1)
                        .addGap(18, 18, 18)
                        .addComponent(chk2)
                        .addGap(18, 18, 18)
                        .addComponent(chk3)
                        .addGap(18, 18, 18)
                        .addComponent(chk4)
                        .addGap(18, 18, 18)
                        .addComponent(chk5))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(proB, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblImages)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        Inicio inicio = new Inicio();
        this.setVisible(false);
        inicio.setVisible(true);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void chk1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chk1ActionPerformed

    private void cmbUserItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbUserItemStateChanged
       Categorias();
    }//GEN-LAST:event_cmbUserItemStateChanged

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        if(cmbUser.getSelectedIndex() != 0 && cmbCategoria.getSelectedIndex() != 0) {
            imagenC.AgregarImagenesACola((String)cmbUser.getSelectedItem(), (String)cmbCategoria.getSelectedItem());
            LlenarCola();
            lblImages.setText("0 / "+imagenC.ImagenesCola().getSize());
        } else {
            JOptionPane.showMessageDialog(this, "Debes seleccionar un usuario y su categoria.");
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEjecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEjecutarActionPerformed
        if(chk1.isSelected() || chk2.isSelected() || chk3.isSelected() || chk4.isSelected() || chk5.isSelected()) {
            Thread hiloP = new Thread(this);
            hiloP.start();
        } else {
            JOptionPane.showMessageDialog(this, "Debes seleccionar por lo menos una opción.");
        }
    }//GEN-LAST:event_btnEjecutarActionPerformed

    private void LlenarCola() {
        list.setModel(modelo);

        modelo.clear();
        
        for(int i = 0; i < imagenC.ImagenesCola().getSize(); i++) {
            String ruta = ((Imagen)imagenC.ImagenesCola().get(i)).getRuta().replaceAll("^[/\\\\\\\\]?(?:.+[/\\\\\\\\]+?)?(.+?)[/\\\\\\\\]?$", "$1");
            modelo.addElement(ruta);
        }
        
    }
    
    private void DatosUsuario() {
        cmbUser.addItem("SELECCIONA UN USUARIO");
        for(int i = 0; i < userC.Usuarios().getSize(); i++) {
            cmbUser.addItem(((Usuario)userC.Usuarios().get(i)).usuario);
        }
    }
    
    private void Categorias() {
        if(cmbUser.getSelectedIndex() != 0) {
            cmbCategoria.removeAllItems();
            cmbCategoria.addItem("SELECCIONA UNA CATEGORIA");
            categoriaC.CategoriaUsuario((String)cmbUser.getSelectedItem());
            for(int i = 0; i < categoriaC.ObtenerCategorias().size(); i++) {
                cmbCategoria.addItem(categoriaC.ObtenerCategorias().get(i).getNombre());
            }
        } else {
            cmbCategoria.removeAllItems();
            cmbCategoria.addItem("SELECCIONA UNA CATEGORIA");
        }
    }
    
    private void Resetear() {
        proB.setValue(0);
        lblImages.setText("0 / 0");
        chk1.setSelected(false);
        chk2.setSelected(false);
        chk3.setSelected(false);
        chk4.setSelected(false);
        chk5.setSelected(false);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Convertidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Convertidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Convertidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Convertidor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Convertidor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEjecutar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JCheckBox chk1;
    private javax.swing.JCheckBox chk2;
    private javax.swing.JCheckBox chk3;
    private javax.swing.JCheckBox chk4;
    private javax.swing.JCheckBox chk5;
    private javax.swing.JComboBox<String> cmbCategoria;
    private javax.swing.JComboBox<String> cmbUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblImages;
    private javax.swing.JList<String> list;
    private javax.swing.ButtonGroup opcionesI;
    private javax.swing.JProgressBar proB;
    private javax.swing.JTextArea textA;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        int i = 0;
        int cont = 0;
        int size = imagenC.ImagenesCola().getSize();
        //for(int i = 0; i < imagenC.ImagenesCola().getSize(); i++) {
        try {
            while(imagenC.ImagenesCola().getSize() >= 0){
                i = imagenC.ImagenesCola().getSize()-1;
                String ruta = ((Imagen)imagenC.ImagenesCola().get(i)).getRuta();
                System.out.println(ruta);
                String extension = ruta.replaceAll("^.*\\.(.*)$", "$1");

                if(chk1.isSelected()) {
                    if(extension.equals("jpg")) {
                        JPEGtoBMPImage image = new JPEGtoBMPImage(ruta);
                        Principal hilo1;
                        hilo1 = new Principal(image, textA);
                        hilo1.start();
                    } else if(extension.equals("bmp")) {
                        BMPtoJPEGImage image = new BMPtoJPEGImage(ruta);
                        Principal hilo1;
                        hilo1 = new Principal(image, textA);
                        hilo1.start();
                    }
                }
                if(chk2.isSelected()) {
                    try {
                        JPEGImageCopy imageCopy = new JPEGImageCopy(ruta);
                        HiloD hilo2;
                        hilo2 = new HiloD(imageCopy, textA);
                        hilo2.start();
                    } catch (Exception e) {
                    }

                }
                if(chk3.isSelected()) {
                    JPEGImageHandlerColors image = new JPEGImageHandlerColors(ruta);
                    HiloT hilo3;
                    hilo3 = new HiloT(image, textA);
                    hilo3.start();
                }
                if(chk4.isSelected()) {
                    JPEGImageHandlerRotator image = new JPEGImageHandlerRotator(ruta);
                    HiloC hilo4;
                    hilo4 = new HiloC(image, textA);
                    hilo4.start();
                }
                if(chk5.isSelected()) {
                    JPEGImageHandlerBN image = new JPEGImageHandlerBN(ruta);
                    HiloCN hilo5;
                    hilo5 = new HiloCN(image, textA);
                    hilo5.start();
                }
                try {
                    Thread.sleep(1000);
                } catch (InterruptedException ex) {
                    Logger.getLogger(Convertidor.class.getName()).log(Level.SEVERE, null, ex);
                }
                cont++;
                proB.setValue((int)(cont*100)/size);
                lblImages.setText(cont+" / "+size);
                imagenC.ImagenesCola().delete(ruta);                
                LlenarCola();
                
            }
            
        } catch (Exception ex) {
            
        }
        JOptionPane.showMessageDialog(this, "Proceso terminado. Imagenes convertidas.");
        Resetear();
    }
}
