/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto2.vista;

import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import proyecto2.handlers.BmpHandlerCopy;
import proyecto2.handlers.JPEGHandler;
import proyecto2.handlersImage.BMPtoJPEGImage;
import proyecto2.handlersImage.JPEGImageCopy;
import proyecto2.handlersImage.JPEGImageHandlerBN;
import proyecto2.handlersImage.JPEGImageHandlerColors;
import proyecto2.handlersImage.JPEGImageHandlerRotator;
import proyecto2.handlersImage.JPEGtoBMPImage;

/**
 *
 * @author JD
 */
public class Editor extends javax.swing.JFrame {

    /**
     * Creates new form Editor
     */
    
    JFileChooser fc = new JFileChooser();
    
    ImageIcon image;
    
    String preview;
    String extension = "";
    
    public Editor() {
        initComponents();
        this.getContentPane().setBackground(new Color(255,244,203));
        ValoresButtons();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        opciones = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnSeleccionar = new javax.swing.JButton();
        lblImagen = new javax.swing.JLabel();
        lblRuta = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        opcD = new javax.swing.JRadioButton();
        opcU = new javax.swing.JRadioButton();
        opcCu = new javax.swing.JRadioButton();
        opcT = new javax.swing.JRadioButton();
        opcCi = new javax.swing.JRadioButton();
        btnEjecutar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 244, 203));

        jPanel1.setBackground(new java.awt.Color(255, 233, 179));

        btnSeleccionar.setBackground(new java.awt.Color(255, 221, 154));
        btnSeleccionar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnSeleccionar.setForeground(new java.awt.Color(0, 0, 0));
        btnSeleccionar.setText("SELECCIONAR IMAGEN");
        btnSeleccionar.setFocusPainted(false);
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });

        lblImagen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        lblRuta.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        lblRuta.setForeground(new java.awt.Color(0, 0, 0));
        lblRuta.setText("RUTA IMAGEN");

        btnRegresar.setBackground(new java.awt.Color(255, 221, 154));
        btnRegresar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(0, 0, 0));
        btnRegresar.setText("REGRESAR");
        btnRegresar.setFocusPainted(false);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblImagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSeleccionar, javax.swing.GroupLayout.DEFAULT_SIZE, 309, Short.MAX_VALUE)
                    .addComponent(lblRuta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRegresar))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(lblImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblRuta)
                .addGap(52, 52, 52)
                .addComponent(btnSeleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 244, 203));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("OPCIONES");

        opciones.add(opcD);
        opcD.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        opcD.setForeground(new java.awt.Color(0, 0, 0));
        opcD.setText("COPIA JPEG");
        opcD.setFocusPainted(false);
        opcD.setOpaque(false);

        opciones.add(opcU);
        opcU.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        opcU.setForeground(new java.awt.Color(0, 0, 0));
        opcU.setText("JPEG A BMP Y VICEVERSA");
        opcU.setFocusPainted(false);
        opcU.setOpaque(false);

        opciones.add(opcCu);
        opcCu.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        opcCu.setForeground(new java.awt.Color(0, 0, 0));
        opcCu.setText("MODIFICAR IMAGEN");
        opcCu.setFocusPainted(false);
        opcCu.setOpaque(false);

        opciones.add(opcT);
        opcT.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        opcT.setForeground(new java.awt.Color(0, 0, 0));
        opcT.setText("ROJO - VERDE - AZUL - SEPIA");
        opcT.setFocusPainted(false);
        opcT.setOpaque(false);

        opciones.add(opcCi);
        opcCi.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        opcCi.setForeground(new java.awt.Color(0, 0, 0));
        opcCi.setText("BLANCO Y NEGRO");
        opcCi.setFocusPainted(false);
        opcCi.setOpaque(false);

        btnEjecutar.setBackground(new java.awt.Color(255, 221, 154));
        btnEjecutar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnEjecutar.setForeground(new java.awt.Color(0, 0, 0));
        btnEjecutar.setText("EJECUTAR");
        btnEjecutar.setFocusPainted(false);
        btnEjecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEjecutarActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(opcU, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(opcT, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(opcCi, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(opcCu, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(opcD, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(btnEjecutar, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jLabel1)))
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(opcU)
                .addGap(27, 27, 27)
                .addComponent(opcD)
                .addGap(43, 43, 43)
                .addComponent(opcT)
                .addGap(35, 35, 35)
                .addComponent(opcCu)
                .addGap(35, 35, 35)
                .addComponent(opcCi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEjecutar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        Inicio inicio = new Inicio();
        this.setVisible(false);
        inicio.setVisible(true);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed
        fc.setDialogTitle("Buscar imagen");
        
        if(fc.showOpenDialog(this) ==  JFileChooser.APPROVE_OPTION) {
            preview = fc.getSelectedFile().toString();
            extension = preview.replaceAll("^.*\\.(.*)$", "$1");
            setImageLabel(lblImagen, preview);
            lblRuta.setText(preview);
        }
    }//GEN-LAST:event_btnSeleccionarActionPerformed

    private void btnEjecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEjecutarActionPerformed
        if(opciones.getSelection() != null && !extension.equals("")) {
            switch(opciones.getSelection().getActionCommand()) {
                case "JPEGABMP": 
                    
                        if(extension.equals("jpg")) {
                            JPEGtoBMPImage imageJPGBMP = new JPEGtoBMPImage(preview);
                            try {
                                JPEGHandler.runHandler(imageJPGBMP);
                                JOptionPane.showMessageDialog(this, "Imagen generada con exito. Se guardó en la carpeta imagenes.");
                            } catch (Exception ex) {
                                ex.printStackTrace();
                            }
                        } else if(extension.equals("bmp")) {
                            BMPtoJPEGImage imageBMPJPEG = new BMPtoJPEGImage(preview);
                            try {
                                JPEGHandler.runHandler(imageBMPJPEG);
                                JOptionPane.showMessageDialog(this, "Imagen generada con exito. Se guardó en la carpeta imagenes.");
                            } catch (Exception ex) {
                                ex.printStackTrace();
                            }
                        }
                    
                    break; 
                case "COPIAJPEG":
                    JPEGImageCopy imageCopy = new JPEGImageCopy(preview);
                    try {
                                JPEGHandler.runHandler(imageCopy);
                                JOptionPane.showMessageDialog(this, "Imagen copiada. Se guardó en la carpeta imagenes.");
                            } catch (Exception ex) {
                                ex.printStackTrace();
                            }
                    break;
                case "RVAS":
                    if(extension.equals("jpg")) {
                        JPEGImageHandlerColors imageRGBS = new JPEGImageHandlerColors(preview);
                        try {
                            JPEGHandler.runHandler(imageRGBS);
                            JOptionPane.showMessageDialog(this, "Imagenes generadas con exito. Se guardaron en la carpeta imagenes.");
                        }catch (Exception ex) {
                            ex.printStackTrace();
                        }
                        
                    }else {
                        JOptionPane.showMessageDialog(this, "La imagen debe ser JPG.");
                    }
                    break; 
                case "MODIFICAR":
                    if(extension.equals("jpg")) {
                        JPEGImageHandlerRotator imageRotar = new JPEGImageHandlerRotator(preview);
                        try {
                            JPEGHandler.runHandler(imageRotar);
                            JOptionPane.showMessageDialog(this, "Imagenes generadas con exito. Se guardaron en la carpeta imagenes.");
                        }catch (Exception ex) {
                            ex.printStackTrace();
                        }
                        
                    }else {
                        JOptionPane.showMessageDialog(this, "La imagen debe ser JPG.");
                    }
                    
                    break;
                case "BLANCONEGRO":
                    if (!extension.equals("jpg")) {
                        JOptionPane.showMessageDialog(this, "La imagen debe ser JPG.");
                    } else {
                        JPEGImageHandlerBN imageHBN = new JPEGImageHandlerBN(preview);
                        try {
                            JPEGHandler.runHandler(imageHBN);
                            JOptionPane.showMessageDialog(this, "Imagen generada con exito. Se guardó en la carpeta imagenes.");
                        } catch (Exception ex) {
                            ex.printStackTrace();
                        }
                    }
                        
                    break;
                    
                default: 
                    break;
            }
        } else {
            JOptionPane.showMessageDialog(this, "Debes seleccionar una imagen y la opción.");
        }
        
    }//GEN-LAST:event_btnEjecutarActionPerformed
    
    private void setImageLabel(JLabel labelName, String root) {
        if(!extension.equals("bmp")) {
            image = new ImageIcon(root);
            Icon icon = new ImageIcon(image.getImage().getScaledInstance(labelName.getWidth(), labelName.getHeight(), Image.SCALE_DEFAULT));
            labelName.setIcon(icon);
        } else {

            try {
                Icon icon = new ImageIcon(ImageIO.read(fc.getSelectedFile()).getScaledInstance(labelName.getWidth(), labelName.getHeight(), Image.SCALE_DEFAULT));
                labelName.setIcon(icon);
            } catch (IOException ex) {
                Logger.getLogger(Editor.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }
    
    private void ValoresButtons() {
        opcU.setActionCommand("JPEGABMP");
        opcD.setActionCommand("COPIAJPEG");
        opcT.setActionCommand("RVAS");
        opcCu.setActionCommand("MODIFICAR");
        opcCi.setActionCommand("BLANCONEGRO");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Editor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEjecutar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblImagen;
    private javax.swing.JLabel lblRuta;
    private javax.swing.JRadioButton opcCi;
    private javax.swing.JRadioButton opcCu;
    private javax.swing.JRadioButton opcD;
    private javax.swing.JRadioButton opcT;
    private javax.swing.JRadioButton opcU;
    private javax.swing.ButtonGroup opciones;
    // End of variables declaration//GEN-END:variables
}
